version: '3.7'

#docker network create --attachable project_network

services:

  frontend:
    build:
      context: /frontend-vue
      dockerfile: Dockerfile
    container_name: 'frontend-vue'
    ports:
      - "8080:80"
    networks:
      project_network:
    depends_on:
      - api

  api:
    build:
      context: /GeationBackEnd
      dockerfile: Dockerfile
    container_name: 'backend-spring'
    image: backend-spring
    networks:
      project_network:
    ports:
      - "8443:8443"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres:14
    environment:
      POSTGRES_DB: contactlist
      POSTGRES_USER: caleb
      POSTGRES_PASSWORD: 2892
    ports:
      - "5432:5432"
    networks:
      project_network:
networks:
  project_network:
    external: true
